export const LOAD_PRODUCT_DATA = "LOAD_PRODUCT_DATA";
export const LOAD_PRODUCT_DETAILS = "LOAD_PRODUCT_DETAILS";
export const EMPTY_PRODUCT_LIST = "EMPTY_PRODUCT_LIST";

export const SET_AUTH_USER = "SET_AUTH_USER";

// Add to Cart Controller
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const FETCH_CART_FOR_CURRENT_USER = "FETCH_CART_FOR_CURRENT_USER";
export const EMPTY_CART = "EMPTY_CART";

export const ORDER_TO_CONFIRM = "ORDER_TO_CONFIRM";
export const ORDER_HISTORY_DATA = "ORDER_HISTORY_DATA";