export const ADD_TO_CART = "ADD_TO_CART";

export const LOAD_PRODUCT_DATA = "LOAD_PRODUCT_DATA";
export const LOAD_PRODUCT_DETAILS = "LOAD_PRODUCT_DETAILS";

export const SET_AUTH_USER = "SET_AUTH_USER";